# Generated by Django 5.1.1 on 2024-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_storage", "0003_alter_data_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="file",
            field=models.CharField(max_length=100),
        ),
    ]
