# Generated by Django 5.1.1 on 2024-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_storage", "0004_alter_data_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
